### ISSUE TITLE
[OreAnnouncer] Failed to load libraries, the plugin will be stopped

### ISSUE THREAD

**Issue by lamya3** [AlessioDP/OreAnnouncer#158]
```
[00:16:30 ERROR]: [OreAnnouncer] Failed to initialize library manager
com.alessiodp.oreannouncer.core.common.addons.external.slimjar.resolver.UnresolvedDependencyException: Could not resolve dependency : com.zaxxer:HikariCP:5.0.1
        at com.alessiodp.oreannouncer.core.common.addons.external.slimjar.downloader.URLDependencyDownloader.lambda$download$0(URLDependencyDownloader.java:76) ~[OreAnnouncer-2.8.5.jar:?]
        at java.util.Optional.orElseThrow(Optional.java:403) ~[?:?]
        at com.alessiodp.oreannouncer.core.common.addons.external.slimjar.downloader.URLDependencyDownloader.download(URLDependencyDownloader.java:76) ~[OreAnnouncer-2.8.5.jar:?]
        at com.alessiodp.oreannouncer.core.common.addons.external.slimjar.injector.helper.InjectionHelper.fetch(InjectionHelper.java:45) ~[OreAnnouncer-2.8.5.jar:?]
        at com.alessiodp.oreannouncer.core.common.addons.external.slimjar.injector.SimpleDependencyInjector.injectDependencies(SimpleDependencyInjector.java:58) ~[OreAnnouncer-2.8.5.jar:?]
        at com.alessiodp.oreannouncer.core.common.addons.external.slimjar.injector.SimpleDependencyInjector.inject(SimpleDependencyInjector.java:52) ~[OreAnnouncer-2.8.5.jar:?]
        at com.alessiodp.oreannouncer.core.common.addons.external.slimjar.app.builder.InjectingApplicationBuilder.buildApplication(InjectingApplicationBuilder.java:65) ~[OreAnnouncer-2.8.5.jar:?]
        at com.alessiodp.oreannouncer.core.common.addons.external.slimjar.app.builder.ApplicationBuilder.build(ApplicationBuilder.java:462) ~[OreAnnouncer-2.8.5.jar:?]
        at com.alessiodp.oreannouncer.core.common.libraries.LibraryManager.init(LibraryManager.java:40) ~[OreAnnouncer-2.8.5.jar:?]
        at com.alessiodp.oreannouncer.core.common.ADPPlugin.loading(ADPPlugin.java:63) ~[OreAnnouncer-2.8.5.jar:?]
        at com.alessiodp.oreannouncer.core.bukkit.bootstrap.ADPBukkitBootstrap.onLoad(ADPBukkitBootstrap.java:33) ~[OreAnnouncer-2.8.5.jar:?]
        at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:59) ~[leaves-1.20.1.jar:git-Leaves-"847357b"]
        at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:18) ~[leaves-1.20.1.jar:git-Leaves-"847357b"]
        at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:40) ~[leaves-1.20.1.jar:git-Leaves-"847357b"]
        at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:36) ~[leaves-1.20.1.jar:git-Leaves-"847357b"]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.loadPlugins(CraftServer.java:517) ~[leaves-1.20.1.jar:git-Leaves-"847357b"]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:278) ~[leaves-1.20.1.jar:git-Leaves-"847357b"]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1095) ~[leaves-1.20.1.jar:git-Leaves-"847357b"]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:309) ~[leaves-1.20.1.jar:git-Leaves-"847357b"]
        at java.lang.Thread.run(Thread.java:1570) ~[?:?]
[00:16:30 ERROR]: [OreAnnouncer] Failed to load libraries, the plugin will be stopped
```
How can I fix that?

**Comment by lamya3** [comment]
LeavesMC 1.20.1
OreAnnouncer-2.8.5 + LastLoginAPI-1.7.4 (throw same error)

**Comment by AlessioDP** [comment]
Can you try again, I changed some settings in my repository to correctly mirror the dependency from Maven Central.

**Comment by lamya3** [comment]
> 你能再试一次吗？我更改了存储库中的某些设置，以正确镜像来自 Maven Central 的依赖项。

Thank you.  No errors when running again
