### ISSUE TITLE
v2.5.4 doesn't load

### ISSUE THREAD

**Issue by d00mfish** [AlessioDP/OreAnnouncer#25]
We upgraded to the new ore announcer version, but it won't load. We regenerated the config but that didnt help. The latest version of Paper 1.15.2 is used.
Error:
`>.... [10:49:13 INFO]: [OreAnnouncer] Enabling OreAnnouncer v2.5.4
>.... [10:49:13 INFO]: [OreAnnouncer] Initializing OreAnnouncer 2.5.4
>.... [10:49:13 INFO]: [OreAnnouncer] Downloaded library https://repo1.maven.org/maven2/com/h2database/h2/1.4.200/h2-1.4.200.jar
>.... [10:49:13 ERROR]: Error occurred while enabling OreAnnouncer v2.5.4 (Is it up to date?)
java.lang.NoClassDefFoundError: com/alessiodp/oreannouncer/libs/slf4j/LoggerFactory
at com.alessiodp.oreannouncer.libs.jdbi.v3.core.Jdbi.<clinit>(Jdbi.java:56) ~[?:?]
at com.alessiodp.oreannouncer.core.common.storage.sql.connection.H2ConnectionFactory.init(H2ConnectionFactory.java:34) ~[?:?]
at com.alessiodp.oreannouncer.core.common.storage.dispatchers.SQLDispatcher.init(SQLDispatcher.java:41) ~[?:?]
at com.alessiodp.oreannouncer.core.common.storage.DatabaseManager.init(DatabaseManager.java:44) ~[?:?]
at com.alessiodp.oreannouncer.core.common.storage.DatabaseManager.reload(DatabaseManager.java:77) ~[?:?]
at com.alessiodp.oreannouncer.common.OreAnnouncerPlugin.loadCore(OreAnnouncerPlugin.java:55) ~[?:?]
at com.alessiodp.oreannouncer.bukkit.BukkitOreAnnouncerPlugin.loadCore(BukkitOreAnnouncerPlugin.java:50) ~[?:?]
at com.alessiodp.oreannouncer.core.common.ADPPlugin.handle(ADPPlugin.java:117) ~[?:?]
at com.alessiodp.oreannouncer.core.common.ADPPlugin.enabling(ADPPlugin.java:60) ~[?:?]
at com.alessiodp.oreannouncer.core.bukkit.bootstrap.ADPBukkitBootstrap.onEnable(ADPBukkitBootstrap.java:32) ~[?:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.15.2.jar:git-Paper-298]
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:364) ~[patched_1.15.2.jar:git-Paper-298]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.15.2.jar:git-Paper-298]
at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugin(CraftServer.java:472) ~[patched_1.15.2.jar:git-Paper-298]
at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugins(CraftServer.java:386) ~[patched_1.15.2.jar:git-Paper-298]
at org.bukkit.craftbukkit.v1_15_R1.CraftServer.reload(CraftServer.java:893) ~[patched_1.15.2.jar:git-Paper-298]
at org.bukkit.Bukkit.reload(Bukkit.java:666) ~[patched_1.15.2.jar:git-Paper-298]
at org.bukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:54) ~[patched_1.15.2.jar:git-Paper-298]
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.15.2.jar:git-Paper-298]
at org.bukkit.craftbukkit.v1_15_R1.CraftServer.dispatchCommand(CraftServer.java:761) ~[patched_1.15.2.jar:git-Paper-298]
at net.minecraft.server.v1_15_R1.PlayerConnection.handleCommand(PlayerConnection.java:1860) ~[patched_1.15.2.jar:git-Paper-298]
at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:1668) ~[patched_1.15.2.jar:git-Paper-298]
at net.minecraft.server.v1_15_R1.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[patched_1.15.2.jar:git-Paper-298]
at net.minecraft.server.v1_15_R1.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.15.2.jar:git-Paper-298]
at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23) ~[patched_1.15.2.jar:git-Paper-298]
at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18) ~[patched_1.15.2.jar:git-Paper-298]
at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.15.2.jar:git-Paper-298]
at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.15.2.jar:git-Paper-298]
at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.15.2.jar:git-Paper-298]
at net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:1097) ~[patched_1.15.2.jar:git-Paper-298]
at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:1090) ~[patched_1.15.2.jar:git-Paper-298]
at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeAll(IAsyncTaskHandler.java:95) ~[patched_1.15.2.jar:git-Paper-298]
at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1224) ~[patched_1.15.2.jar:git-Paper-298]
at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:962) ~[patched_1.15.2.jar:git-Paper-298]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]
Caused by: java.lang.ClassNotFoundException: com.alessiodp.oreannouncer.libs.slf4j.LoggerFactory
at java.net.URLClassLoader.findClass(URLClassLoader.java:382) ~[?:1.8.0_242]
at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:173) ~[patched_1.15.2.jar:git-Paper-298]
at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101) ~[patched_1.15.2.jar:git-Paper-298]
at java.lang.ClassLoader.loadClass(ClassLoader.java:419) ~[?:1.8.0_242]
at java.lang.ClassLoader.loadClass(ClassLoader.java:352) ~[?:1.8.0_242]
... 35 more
>.... [10:49:13 INFO]: [OreAnnouncer] Disabling OreAnnouncer v2.5.4
>.... [10:49:13 INFO]: [OreAnnouncer] Disabling OreAnnouncer
>.... [10:49:13 INFO]: [OreAnnouncer] OreAnnouncer disabled`

**Comment by AlessioDP** [comment]
You must delete the folder lib in OreAnnouncer plugins folder ;)

**Comment by d00mfish** [comment]
Thanks a lot, now it works like a charm :)
